const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');
require.extensions['.ts']=(module,file)=>module._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true,resolveJsonModule:true}}).outputText,file);
const {buildFuelWorkbook}=require('../lib/fuel-workbook.ts');const {createFuelWorkbook}=require('../lib/export-fuel-workbook.ts');const {defaultSettings,numericFields,fiscalMonths}=require('../lib/official-fuel.ts');const ExcelJS=require('exceljs');
const asset={...Object.fromEntries(numericFields.map(k=>[k,null])),id:'v1',kind:'vehicle',name:'รถบรรทุก',brand:'Toyota',code:'กข 1234',cylinders:'4',fuel:'ดีเซล',condition:'ปกติ',remark:'',used1:10,used2:20,startMileage:1000,endMileage:1300,quota:100,oilQuota:5,oilUsed:0};
const snapshots=fiscalMonths.map(month=>({fiscal_year:2569,month,settings:defaultSettings,rows:[asset,{...asset,id:'m1',kind:'machine',code:'12562',name:'เครื่องพ่นหมอกควัน'}]}));
test('suite includes machine annual/monthly, per plate, method and summary with selected fiscal dates',()=>{const s=buildFuelWorkbook(snapshots,2569,defaultSettings);assert.equal(s.length,5);assert.equal(s[2].name,'กข 1234');assert.equal(s[2].rows[1][0],'ปีงบประมาณ 2569');assert.equal(s[2].rows[8][1],'ตุลาคม 2568');assert.equal(s[2].rows[19][1],'กันยายน 2569');assert.equal(s[4].rows[7][11],360);assert.equal(s[4].rows[7][13],10);assert.equal(s[0].rows[5][5],1200);});
test('missing month is unknown in annual totals, zero consumption never divides by zero',()=>{const partial=buildFuelWorkbook(snapshots.slice(0,11),2569,defaultSettings);assert.equal(partial.at(-1).rows[7][11],'—');const zero=buildFuelWorkbook(snapshots.map(s=>({...s,rows:[{...asset,used1:0,used2:0}]})),2569,defaultSettings);assert.equal(zero[2].formulas.M9.result,'—');});
test('Excel round trip preserves template merges, numeric values, formulas, Thai labels and print area without sample data',async()=>{const s=buildFuelWorkbook(snapshots,2569,{...defaultSettings,chief:'ทดสอบ'});const w=await createFuelWorkbook(s);const bytes=await w.xlsx.writeBuffer();const read=new ExcelJS.Workbook();await read.xlsx.load(bytes);const v=read.getWorksheet('กข 1234');assert.equal(v.getCell('K9').value,30);assert.equal(v.getCell('M9').value.result,10);assert.equal(v.getCell('A2').value,'ปีงบประมาณ 2569');assert.ok(v.model.merges.includes('A1:M1'));assert.equal(v.pageSetup.orientation,'landscape');assert.ok(v.pageSetup.printArea);assert.equal(v.getCell('N9').value,null);assert.ok(!read.worksheets.some(s=>s.name.includes(' 68')));assert.ok(v.getCell('K9').border.top);});
test('selected month range limits rows and totals in preview and workbook',()=>{const s=buildFuelWorkbook(snapshots,2569,defaultSettings,[10,11]);assert.equal(s[2].rows[1][0],'ช่วง ตุลาคม 2568 ถึง พฤศจิกายน 2568');assert.equal(s[2].rows[8][1],'ตุลาคม 2568');assert.equal(s[2].rows[9][1],'พฤศจิกายน 2568');assert.ok(!s[2].rows.some(r=>r[1]==='ธันวาคม 2568'));assert.equal(s.at(-1).rows[7][11],60);assert.equal(s[0].rows[5][5],200);const missing=buildFuelWorkbook(snapshots.slice(0,1),2569,defaultSettings,[10,11]);assert.equal(missing.at(-1).rows[7][11],'—');});
