'use client';
import { Fragment, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Building2, CalendarDays, Car, CheckCircle2, ChevronDown, CircleHelp, FileText, Loader2, Plus, Printer, Save, Settings2, Trash2, Wrench } from 'lucide-react';
import { months, fiscalMonths, fiscalDates, defaultSettings, used, balance1, balance2, numericFields, type FuelRow, type Snapshot, type ReportSettings } from '@/lib/official-fuel';
import './report.css';
import WorkbookPreview from './WorkbookPreview';
import { buildFuelWorkbook } from '@/lib/fuel-workbook';
import { exportOfficialExcel } from '@/lib/export-official-excel';
const formats = ['บันทึกข้อความ','รับ–ใช้–คงเหลือรายเดือน','R03 จำแนกทรัพย์สิน','บัญชียานพาหนะรายปี','บัญชียานพาหนะรายเดือน','บัญชีเครื่องจักรรายปี','บัญชีเครื่องจักรรายเดือน','วิธีคิดค่าเฉลี่ยการใช้น้ำมัน'];
const labels: Record<string,string> = {name:'ชื่อ/ประเภทยานพาหนะหรือเครื่องจักร',brand:'ยี่ห้อ',code:'ทะเบียน/หมายเลขเครื่อง',assetCode:'รหัสประเภททรัพย์สิน',cylinders:'จำนวนสูบ',fuel:'ประเภทน้ำมัน',fuelCode:'รหัสน้ำมัน',oilName:'ชื่อน้ำมันหล่อลื่น',oilCode:'รหัสน้ำมันหล่อลื่น',oilCost:'มูลค่าหล่อลื่นที่ใช้ (บาท)',condition:'สภาพการใช้งาน',remark:'หมายเหตุ',opening:'คงเหลือต้นเดือน (ลิตร)',received1:'ได้รับงวดแรก (ลิตร)',used1:'ใช้จริงงวดแรก (ลิตร)',received2:'ได้รับงวดหลัง (ลิตร)',used2:'ใช้จริงงวดหลัง (ลิตร)',startMileage:'เลขไมล์ต้นเดือน',endMileage:'เลขไมล์ปลายเดือน',quota:'โควตาเชื้อเพลิงต่อเดือน (ลิตร)',oilQuota:'โควตาหล่อลื่นต่อเดือน (ลิตร)',oilUsed:'หล่อลื่นที่ใช้ (ลิตร)',cost:'มูลค่าน้ำมันที่ใช้ (บาท)'};
const settingsLabels: Record<keyof ReportSettings,string> = {department:'ฝ่าย',office:'สำนักงาน',reporter:'ชื่อผู้จัดทำ',position:'ตำแหน่งผู้จัดทำ',chief:'ชื่อผู้รายงาน/หัวหน้าฝ่าย',chiefPosition:'ตำแหน่งผู้รายงาน',memoNumber:'เลขที่หนังสือ',memoDate:'วันที่หนังสือ',phone:'โทรศัพท์',references:'หนังสืออ้างอิง/ข้อความประกอบ'};
const n = (v: number|null|undefined) => v == null ? '—' : v.toLocaleString('th-TH',{maximumFractionDigits:2});
function sum(values:(number|null)[]) { return values.some(v=>v === null) ? null : values.reduce<number>((s,v)=>s+(v || 0),0); }
export default function OfficialFuelPage() {
 const [downloadType,setDownloadType]=useState('pdf');
 const [exporting,setExporting]=useState(false);
 async function downloadReport(){
  if(downloadType==='pdf'){window.print();return;}
  const paper=document.querySelector<HTMLElement>('.official-fuel .paper');
  if(!paper)return;
  setExporting(true);
  try {
   if(format>=3){
    const {downloadFuelWorkbook}=await import('@/lib/export-fuel-workbook');
    const sheets=(format===4||format===6)&&selected?buildFuelWorkbook(all.map(s=>({...s,rows:s.rows.filter(r=>r.id===selected)})),year,settings):workbookSheets;
    const exportSheets=format===7?sheets.filter(s=>s.kind==='method'):format===3?[sheets[sheets.length-1]]:format===4?sheets.filter(s=>s.kind==='vehicle'):format===5?[sheets[0]]:[sheets[1]];
    await downloadFuelWorkbook(exportSheets,`${formats[format]}-${year}`);
   }else await exportOfficialExcel(paper,`${formats[format]}-${year}-${month}`);
  }
  catch {setError('ดาวน์โหลด Excel ไม่สำเร็จ กรุณาลองใหม่');}
  finally {setExporting(false);}
 }
 const today = new Date();
 const [year,setYear] = useState(today.getFullYear()+543+(today.getMonth()>=9?1:0)); const [month,setMonth] = useState(today.getMonth()+1);
 const [rows,setRows] = useState<FuelRow[]>([]); const [snapshots,setSnapshots] = useState<Snapshot[]>([]); const [settings,setSettings] = useState(defaultSettings);
 const [format,setFormat] = useState(1); const [selected,setSelected] = useState(''); const [category,setCategory] = useState(''); const [fuelFilter,setFuelFilter] = useState('');
 const [unallocated,setUnallocated] = useState<{id:string;date:string;code:string;liters:number|null;number:string}[]>([]);
 const [workspaceTab,setWorkspaceTab] = useState<'preview'|'data'>('preview');
 const [loading,setLoading] = useState(true); const [saving,setSaving] = useState(false); const [error,setError] = useState(''); const [notice,setNotice] = useState(''); const [dirty,setDirty] = useState(false);
 useEffect(()=>{let active=true; setLoading(true);setError('');setNotice('');
 fetch(`/api/admin/reports/fuel/official?year=${year}&month=${month}`).then(async res=>{const data=await res.json();if(!res.ok)throw new Error(data.error);if(!active)return;
 const saved=data.snapshots.find((s:Snapshot)=>s.month===month);setSnapshots(data.snapshots);setRows(saved?.rows || data.rows);setSettings(saved?.settings || data.snapshots[0]?.settings || data.settings);setDirty(false);
 setNotice(`ดึงรายการน้ำมัน ${data.sourceCount} ใบเบิก พร้อมเลขไมล์จากงานใช้รถแล้ว • ยอดใช้จริงอ้างอิงปริมาณจริงที่บันทึกในใบเบิก ช่องที่ยังไม่มีข้อมูลสามารถเพิ่มเติมได้`);
 setUnallocated(data.unallocatedMachineRequests);
 if(data.unallocatedMachineRequests.length)setNotice((s)=>`${s} • มี ${data.unallocatedMachineRequests.length} ใบเบิกที่ต้องจัดสรรให้เครื่องจักร/ตรวจทะเบียนด้วยตนเอง`);
 }).catch(e=>{if(active){setError(e.message);setRows([]);setSnapshots([]);}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[year,month]);
 const changeRow = (index:number,key:string,value:string) => {setDirty(true);setRows(prev=>prev.map((r,i)=>i===index?{...r,[key]:numericFields.includes(key as typeof numericFields[number]) ? value===''?null:Number(value):value}:r));};
 const save = async()=>{setSaving(true);setError('');try{const snapshot={fiscal_year:year,month,rows,settings};const res=await fetch('/api/admin/reports/fuel/official',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(snapshot)});const data=await res.json();if(!res.ok)throw new Error(data.error);setSnapshots(prev=>[...prev.filter(s=>s.month!==month),snapshot]);setDirty(false);setNotice('บันทึกข้อมูลรายเดือนแล้ว');}catch(e){setError(e instanceof Error?e.message:'บันทึกไม่ได้');}finally{setSaving(false);}};
 const dates=fiscalDates(year,month); const current:Snapshot={fiscal_year:year,month,rows,settings};
 const all=fiscalMonths.map(m=>m===month?current:snapshots.find(s=>s.month===m)).filter((s):s is Snapshot=>!!s);
 const workbookSheets=buildFuelWorkbook(all,year,settings);
 const vehicleRows=rows.filter(r=>r.kind==='vehicle');
 const visible=(format===2?rows:vehicleRows).filter(r=>(!category||r.name===category)&&(!fuelFilter||r.fuel===fuelFilter));
 const assets=Array.from(new Map(all.flatMap(s=>s.rows).filter(r=>r.kind===(format>=5?'machine':'vehicle')).map(r=>[r.id,r])).values());
 const signature=<div className="signature">ลงชื่อ................................................ผู้รายงาน<br/>({settings.chief || '................................................'})<br/>{settings.chiefPosition}<br/>{settings.department}<br/>{settings.office}</div>;
 const header=(title:string,monthly=false)=><header><h2>{title}</h2><p>{monthly?`ประจำเดือน ${months[month-1]} พ.ศ. ${dates.yearBE}`:`ปีงบประมาณ ${year}`}</p><p>{settings.department} {settings.office}</p></header>;
 const table=(head:React.ReactNode,body:React.ReactNode)=><table><thead>{head}</thead><tbody>{body}</tbody></table>;
 const cell=(values:React.ReactNode[],key:string)=><tr key={key}>{values.map((v,i)=><td key={i}>{v}</td>)}</tr>;
 return <div className="official-fuel">
 <div className="controls">
  <div className="report-heading">
   <div><Link href="/admin/reports/fuel" className="back-link"><ArrowLeft size={14}/> รายงานการเบิกน้ำมันเดิม</Link><div className="heading-title"><span className="heading-icon"><FileText size={24}/></span><div><h1>รายงานน้ำมันตามแบบราชการ</h1><p>จัดทำรายงานรถและเครื่องจักร พร้อมเอกสารสำหรับพิมพ์</p></div></div></div>
   <span className="form-count">8 แบบฟอร์ม</span>
  </div>
  <section className="period-panel">
   <div className="period-fields"><label><span>ปีงบประมาณ พ.ศ.</span><input type="number" min="2500" max="2800" value={year} onChange={e=>{if(!dirty||confirm('มีข้อมูลที่ยังไม่บันทึก ต้องการเปลี่ยนปีหรือไม่?'))setYear(Number(e.target.value));}}/></label><label><span>เดือนที่จัดทำรายงาน</span><select value={month} onChange={e=>{if(!dirty||confirm('มีข้อมูลที่ยังไม่บันทึก ต้องการเปลี่ยนเดือนหรือไม่?'))setMonth(Number(e.target.value));}}>{fiscalMonths.map(m=><option key={m} value={m}>{months[m-1]} {fiscalDates(year,m).yearBE}</option>)}</select></label></div>
   <div className="report-actions"><button className="button-secondary" onClick={save} disabled={loading||saving||!!error&&rows.length===0}>{saving?<Loader2 size={17} className="spinning"/>:<Save size={17}/>} {saving?'กำลังบันทึก…':'บันทึกข้อมูล'}</button><select className="download-type" aria-label="ประเภทไฟล์ดาวน์โหลด" value={downloadType} onChange={e=>setDownloadType(e.target.value)}><option value="pdf">PDF (.pdf)</option><option value="excel">Excel (.xlsx)</option></select><button className="button-primary" disabled={loading||!!error||exporting} onClick={downloadReport}>{exporting?<Loader2 size={17} className="spinning"/>:<Printer size={17}/>} {exporting?'กำลังสร้างไฟล์…':downloadType==='pdf'?'บันทึก PDF':'ดาวน์โหลด Excel'}</button></div>
  </section>
  <section className="format-panel format-dropdown-panel"><div className="format-heading"><span className="format-heading-icon"><FileText size={20}/></span><div><h2><label htmlFor="report-format">แบบรายงาน</label></h2><p>เลือกเอกสารที่ต้องการจัดทำ</p></div></div><div className="format-field"><div className="format-select-wrap"><select id="report-format" aria-describedby="report-format-description" className="format-select" value={format} onChange={e=>{setFormat(Number(e.target.value));setCategory('');setFuelFilter('');setSelected('');}}>{formats.map((name,i)=><option key={name} value={i}>{name}</option>)}</select><ChevronDown size={18} aria-hidden="true"/></div><p id="report-format-description" className="format-description">{['หนังสือนำส่งรายงานการใช้น้ำมัน','แสดงยอดรับ ใช้ และคงเหลือ แยกงวดแรกและงวดหลัง','สรุปปริมาณและมูลค่าน้ำมัน จำแนกตามทรัพย์สิน','สรุปการใช้น้ำมันของยานพาหนะตลอดปีงบประมาณ','แสดงรายละเอียดการใช้น้ำมันแต่ละเดือนของยานพาหนะ','สรุปการใช้น้ำมันของเครื่องจักรตลอดปีงบประมาณ','แสดงรายละเอียดการใช้น้ำมันแต่ละเดือนของเครื่องจักร','อธิบายสูตรระยะทางและค่าเฉลี่ย กม./ลิตร'][format]}</p></div><span className="format-period"><CalendarDays size={15}/> {months[month-1]} {dates.yearBE}</span></section>
  {error&&<div role="alert" className="report-alert error-alert">{error}</div>}
  <div className="workspace-navigation"><div className="workspace-tabs" role="tablist" aria-label="จัดทำรายงาน"><button id="preview-tab" role="tab" aria-selected={workspaceTab==='preview'} aria-controls="preview-panel" className={workspaceTab==='preview'?'active':''} onClick={()=>setWorkspaceTab('preview')}><FileText size={16}/> ตัวอย่างรายงาน</button><button id="data-tab" role="tab" aria-selected={workspaceTab==='data'} aria-controls="data-panel" className={workspaceTab==='data'?'active':''} onClick={()=>setWorkspaceTab('data')}><Settings2 size={16}/> ข้อมูลประกอบ <span className="tab-count">{rows.length}</span></button></div><span role="status" className={`save-status ${dirty?'unsaved':''}`}>{loading?<Loader2 size={14} className="spinning"/>:dirty?<span className="status-dot"/>:<CheckCircle2 size={14}/>} {loading?'กำลังโหลด':dirty?'มีการแก้ไขที่ยังไม่บันทึก':'ข้อมูลจากฐานข้อมูล'}</span></div>
  <div className="report-alert info-alert"><CircleHelp size={17}/><span>{notice || 'เลือกเดือนและแบบรายงานเพื่อเริ่มจัดทำเอกสาร'} {workspaceTab==='preview'&&!loading&&<button className="inline-action" onClick={()=>setWorkspaceTab('data')}>ตรวจสอบข้อมูล <ArrowRight size={13}/></button>}</span></div>
  {workspaceTab==='data'&&<section id="data-panel" role="tabpanel" aria-labelledby="data-tab" className="data-panel">
   <details className="editor-section"><summary><span className="summary-icon"><Building2 size={18}/></span><span><strong>ข้อมูลหน่วยงานและผู้ลงนาม</strong><small>รายละเอียดหนังสือและชื่อผู้รายงาน</small></span><ChevronDown size={17}/></summary><div className="field-grid">{Object.entries(settingsLabels).map(([k,label])=><label key={k}><span>{label}</span>{k==='references'?<textarea rows={3} value={settings.references} onChange={e=>{setDirty(true);setSettings({...settings,references:e.target.value});}}/>:<input type={k==='memoDate'?'date':'text'} value={settings[k as keyof ReportSettings]} onChange={e=>{setDirty(true);setSettings({...settings,[k]:e.target.value});}}/>}</label>)}</div></details>
   {unallocated.length>0&&<details className="editor-section"><summary><span className="summary-icon"><Wrench size={18}/></span><span><strong>ใบเบิกที่ต้องจัดสรร / ตรวจสอบทะเบียน</strong><small>{unallocated.length} รายการที่ต้องตรวจสอบ</small></span><ChevronDown size={17}/></summary><p className="editor-help">ใบเบิกที่ระบุหลายเครื่องต้องแยกยอดได้รับแต่ละเครื่องด้วยตนเอง</p><div className="source-table"><table><thead><tr><th>วันที่</th><th>เลขใบเบิก</th><th>ทะเบียน/เครื่อง</th><th>ได้รับ (ลิตร)</th></tr></thead><tbody>{unallocated.map(f=><tr key={f.id}><td>{f.date}</td><td>{f.number}</td><td>{f.code}</td><td>{n(f.liters)}</td></tr>)}</tbody></table></div></details>}
   <div className="section-heading asset-heading"><div><h2>รถและเครื่องจักร</h2><p>กรอกยอดใช้จริงและข้อมูลประกอบของแต่ละรายการ</p></div><button className="button-secondary" onClick={()=>{setDirty(true);setRows([...rows,{id:crypto.randomUUID(),kind:'machine',name:'เครื่องพ่นหมอกควัน',brand:'',code:'',assetCode:'',cylinders:'',fuel:'',fuelCode:'',oilName:'',oilCode:'',condition:'',remark:'',...Object.fromEntries(numericFields.map(k=>[k,null]))} as FuelRow]);}}><Plus size={16}/> เพิ่มรายการ</button></div>
   {rows.map((r,i)=><details className="editor-section asset-editor" key={r.id}><summary><span className="summary-icon">{r.kind==='vehicle'?<Car size={18}/>:<Wrench size={18}/>}</span><span><strong>{r.code || 'รายการใหม่'} <span className="asset-fuel">{r.fuel}</span></strong><small>{r.name} {r.brand}</small></span><span className="asset-usage">ใช้จริง {n(used(r))} ลิตร</span><ChevronDown size={17}/></summary><div className="asset-fields"><label><span>ประเภท</span><select value={r.kind} onChange={e=>changeRow(i,'kind',e.target.value)}><option value="vehicle">ยานพาหนะ</option><option value="machine">เครื่องจักร</option></select></label>{[
    {title:'ข้อมูลทรัพย์สิน',keys:['name','brand','code','assetCode','cylinders','fuel','fuelCode','condition','remark']},
    {title:'ยอดน้ำมันสองงวด',keys:['opening','received1','used1','received2','used2']},
    {title:'เลขไมล์ โควตา และมูลค่า',keys:['startMileage','endMileage','quota','cost']},
    {title:'น้ำมันหล่อลื่น',keys:['oilName','oilCode','oilQuota','oilUsed','oilCost']}
   ].map(group=><fieldset key={group.title}><legend>{group.title}</legend><div className="field-grid">{group.keys.map(k=><label key={k}><span>{labels[k]}</span><input type={numericFields.includes(k as typeof numericFields[number])?'number':'text'} min="0" step="any" placeholder={numericFields.includes(k as typeof numericFields[number])?'ยังไม่มีข้อมูล':''} value={r[k as keyof FuelRow]??''} onChange={e=>changeRow(i,k,e.target.value)}/></label>)}</div></fieldset>)}<div className="asset-footer"><span>คงเหลือปลายเดือน <b>{n(balance2(r))} ลิตร</b></span><button className="button-danger" onClick={()=>{if(confirm('ลบรายการออกจากรายงานเดือนนี้?')){setDirty(true);setRows(rows.filter((_,j)=>j!==i));}}}><Trash2 size={14}/> ลบรายการ</button></div></div></details>)}
   <p className="editor-help">ช่องว่าง = ยังไม่มีข้อมูล • กรอก 0 เมื่อยืนยันว่าไม่มีการใช้ • งวดแรกวันที่ 1–15 และงวดหลังวันที่ 16–สิ้นเดือน</p>
  </section>}
  {workspaceTab==='preview'&&<div className="preview-toolbar"><div><h2><FileText size={17}/> ตัวอย่างก่อนพิมพ์</h2><p>{formats[format]} · {format===0?'A4 แนวตั้ง':'A4 แนวนอน'}</p></div><div className="preview-filters">
   {(format===1||format===2)&&<><label><span>ประเภทรถ / ทรัพย์สิน</span><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">ทุกประเภท</option>{Array.from(new Set((format===2?rows:vehicleRows).map(r=>r.name))).map(v=><option key={v}>{v}</option>)}</select></label><label><span>ประเภทน้ำมัน</span><select value={fuelFilter} onChange={e=>setFuelFilter(e.target.value)}><option value="">ทุกประเภท</option>{Array.from(new Set((format===2?rows:vehicleRows).map(r=>r.fuel))).map(v=><option key={v}>{v}</option>)}</select></label></>}
   {(format===4||format===6)&&<label><span>ทะเบียน / เครื่องจักร</span><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">ทุกรายการ</option>{assets.map(a=><option key={a.id} value={a.id}>{a.code} {a.fuel}</option>)}</select></label>}
  </div></div>}
  {format>=3&&format!==7&&workspaceTab==='preview'&&<div className="year-progress"><span>ข้อมูลปีงบประมาณ {year} <b>{all.length}/12 เดือน</b>{all.length<12?' · ยังไม่ครบปี':''}</span><span>{all.map(s=>months[s.month-1]).join(' · ')}</span></div>}
 </div>
 {!loading&&!error&&<div id="preview-panel" role="tabpanel" aria-labelledby="preview-tab" className={`preview-stage ${workspaceTab==='data'?'preview-inactive':''}`}><div className={`paper ${format===0?'portrait':''}`}>
 {format===3&&<WorkbookPreview sheets={[workbookSheets[workbookSheets.length-1]]}/>}
 {format===7&&<WorkbookPreview sheets={workbookSheets.filter(s=>s.kind==='method')}/>}
 {(format===4||format===5||format===6)&&<WorkbookPreview sheets={(selected&&(format===4||format===6)?buildFuelWorkbook(all.map(s=>({...s,rows:s.rows.filter(r=>r.id===selected)})),year,settings):workbookSheets).filter(s=>format===4?s.kind==='vehicle':s.name===(format===5?'เครื่องพ่นยุง (รายปี)':'เครื่องพ่นยุง (รายเดือน)'))}/>}
 {format===0?<><h1 className="memo-title">บันทึกข้อความ</h1><p><b>ส่วนราชการ</b> {settings.department} {settings.office} โทร. {settings.phone}</p><p><b>ที่</b> {settings.memoNumber} <span className="float-right"><b>วันที่</b> {settings.memoDate?new Date(settings.memoDate+'T12:00:00+07:00').toLocaleDateString('th-TH',{dateStyle:'long'}):'................................'}</span></p><p><b>เรื่อง</b> ขอส่งรายงานการใช้น้ำมัน ประจำเดือน {months[month-1]} {dates.yearBE} และบัญชีแสดงการใช้น้ำมันเชื้อเพลิง ประจำปีงบประมาณ {year}</p><p>เรียน {settings.chiefPosition}</p><p className="indent">{settings.references}</p><p className="indent">ได้จัดทำรายงานการใช้น้ำมันประจำเดือน {months[month-1]} {dates.yearBE} และบัญชีแสดงการใช้น้ำมันเชื้อเพลิงของยานพาหนะและเครื่องจักรและเครื่องทุ่นแรง ประจำปีงบประมาณ {year} ตามแบบฟอร์มที่แนบมาพร้อมนี้</p><p className="indent">จึงเรียนมาเพื่อโปรดพิจารณา</p><div className="signature">({settings.reporter || '................................'})<br/>{settings.position}<br/>{settings.department}<br/>{settings.office}</div>{signature}</>:null}
 {format===1&&<>{header('รายงานการใช้น้ำมัน',true)}<p>ประเภท {category||'ทุกประเภท'} • ประเภทน้ำมันเชื้อเพลิง/น้ำมันหล่อลื่น {fuelFilter||'ทุกประเภท'}</p>{table(<><tr><th rowSpan={2}>ลำดับ</th><th rowSpan={2}>หมายเลขทะเบียน</th><th colSpan={3}>งวดแรก</th><th colSpan={3}>งวดหลัง</th><th rowSpan={2}>ยอดรวมใช้จริง</th><th rowSpan={2}>หมายเหตุ</th></tr><tr>{[1,2].flatMap(v=>['ได้รับ','ใช้','คงเหลือ'].map(t=><th key={v+t}>{t} (ลิตร)</th>))}</tr></>,<>{visible.map((r,i)=>cell([i+1,`${r.code} ${r.brand}`,n(r.received1),n(r.used1),n(balance1(r)),n(r.received2),n(r.used2),n(balance2(r)),n(used(r)),r.remark],r.id))}{cell(['รวม','','','','','','','',n(sum(visible.map(used))), ''],'total')}</>)}{signature}</>}
 {format===2&&<>{header('รายงานการใช้น้ำมันเชื้อเพลิงและหล่อลื่นรายเดือน จำแนกตามรหัสทรัพย์สินและหน่วยงาน (R03)',true)}{table(<tr>{['ทะเบียนทรัพย์สิน','รหัสน้ำมัน','ชื่อน้ำมันเชื้อเพลิงและหล่อลื่น','หน่วยนับ','จำนวน','รวมเงิน (บาท)'].map(t=><th key={t}>{t}</th>)}</tr>,<>{Array.from(new Set(visible.map(r=>r.assetCode+' '+r.name))).map(group=>{const entries=visible.filter(r=>r.assetCode+' '+r.name===group);return <Fragment key={group}>{cell([group,'','','','',''],group)}{entries.map(r=><Fragment key={r.id}>{cell([`${r.code} ${r.brand}`,r.fuelCode,r.fuel,'ลิตร',n(used(r)),n(r.cost)],r.id)}{r.oilName && cell([`${r.code} ${r.brand}`,r.oilCode,r.oilName,'ลิตร',n(r.oilUsed),n(r.oilCost)],r.id+'oil')}</Fragment>)}{cell(['รวมประเภททรัพย์สิน '+group,'','','',n(sum(entries.flatMap(r=>r.oilName?[used(r),r.oilUsed]:[used(r)]))),n(sum(entries.flatMap(r=>r.oilName?[r.cost,r.oilCost]:[r.cost])))],group+'sum')}</Fragment>;})}{cell(['รวมทั้งสิ้น','','','',n(sum(visible.flatMap(r=>r.oilName?[used(r),r.oilUsed]:[used(r)]))),n(sum(visible.flatMap(r=>r.oilName?[r.cost,r.oilCost]:[r.cost])))],'total')}</>)}{signature}</>}
 {rows.length===0&&format!==0&&<p>ไม่มีรายการในเดือนที่เลือก</p>}
 </div></div>}
 </div>;
}
